### ISSUE TITLE
Received 0 indicator in MISP

### ISSUE THREAD

**Issue by PiusO** [cudeso/misp2sentinel#47] opened 2023-07-26 18:58 UTC
Any idea what would cause this error message in the logs after entering python3 script.py - tried to take things into production environment and this has happened. Yet original demo environment is working fine, tested with same app reg credentials.

2023-07-26 18:54:37,748 - misp2sentinel - INFO - Start MISP2Sentinel
2023-07-26 18:54:37,748 - misp2sentinel - INFO - Fetching and parsing data from MISP ...
2023-07-26 18:54:37,748 - misp2sentinel - INFO - Using Microsoft Upload Indicator API
2023-07-26 18:54:38,141 - misp2sentinel - INFO - Received 0 indicators in MISP
2023-07-26 18:54:38,250 - misp2sentinel - INFO - Start uploading indicators
2023-07-26 18:54:38,250 - misp2sentinel - INFO - Finished uploading indicators
2023-07-26 18:54:38,250 - misp2sentinel - INFO - End MISP2Sentinel

**Comment by cudeso** [comment] 2023-07-26 19:52
Looking at the timestamps (almost no time in between queries) this looks like no events are returned by your search query. Can you post the content of `config.misp_event_filters`?

**Comment by PiusO** [comment] 2023-07-26 20:27
Do you mean the below or a dir if so where is that?

misp_event_filters = {
    "published": 1,
    "tags": [ "workflow:state=\"complete\""],
    "enforceWarninglist": True,
    "includeEventTags": True,
    "publish_timestamp": "14d",
}

**Comment by cudeso** [comment] 2023-07-26 20:43
Does you MISP server have recently (14d) published events with the tag `"workflow:state="complete""` or `"workflow:state=\"complete\""`?

**Comment by PiusO** [comment] 2023-07-26 20:53
Not sure i quite understand the question, do you mean the events in "Home" of the GUI? if so no, same with what landed in Sentinel 

Where are you referring to? Is this with one of the py scripts

**Comment by cudeso** [comment] 2023-07-27 06:09
The script pulls the event from the MISP server that you defined in the config file. It uses the `misp_event_filters` as filters for which events it needs to pull. One of those filters is searching for events with a tag complete. 
If there are no events tagged with this tag, then the script does not get results from your MISP server.

One of your filters, for workflow, also has the escaping of the quotes wrong. The quotes around complete in are not escaped, `"workflow:state="complete""` whereas it needs to be as follows: "workflow:state=\"complete\""`. But again, this only works if you have this tag attached to events. If you don't have this tag, then remove it from the config or use another tag for filtering.

**Comment by PiusO** [comment] 2023-07-27 09:47
Makes a lot more sense. 
Why I had no events with that tag I'm not sure, and this also explains why I'm pulling in a lot less events to Sentinel as i previously didn't have these filters.

By this morning I had 17 events with tag completed and exactly 17 were received and then sent.

Two questions:
I can't find info on "workflow state" - what would be the issue with removing this from the filter?
Also why 14d for publish_timestamp - are events that haven't been updated within the last 14 days not pulled in, if so does that not leave out a lot of events. So would it be worth while removing this filter also for the first pull?

Once again thank you

**Comment by cudeso** [comment] 2023-07-27 19:08
There's no problem removing it from the filter. I included it as an example as the MISP [workflow taxonomy](https://www.misp-project.org/taxonomies.html#_workflow) is often used to describe the "state" of an event. You can remove it or replace it with your preference of tags, there's no "logic" attached in the script for this tag. It's only used to describe which events to fetch from MISP.

You can remove the 14d for the first pull, certainly. It's put in the example config as a safeguard for not pulling in all events if you have a larger event database. If you have MISP events that go back 10 years then it's not that all that useful to include all events. But sure, you can remove the 14d, just evaluate how many events you have and if it's worth syncing them all.

**Comment by PiusO** [comment] 2023-08-02 15:57
Pulling in data using STIX module is taking much longer than it did before, taking 2hrs+ to pull logs in without the workflow:state="complete" filter. If I apply the filter, very few come through and not frequently.

Do you have any suggestions for how to get feeds in quicker?

Do you also know of any location where data is being written too that can be deleted, noticed a lot more space is being consumed than before - other than the log file configured for the config.py script?

ms_passiveonly = False              # Graph API only
ms_action = 'alert'                 # Graph API only

ms_api_version = "2022-07-01"       # Upload Indicators API version
ms_max_indicators_request = 100     # Upload Indicators API: Throttle max: 100 indicators per request
ms_max_requests_minute = 100        # Upload Indicators API: Throttle max: 100 requests per minute


####
# MISP section
misp_key = '*****'
misp_domain = '******'
misp_verifycert = False

misp_event_filters = {
    "published": 1,
    #"tags": [ "workflow:state=\"complete\""],
    "enforceWarninglist": True,
    "includeEventTags": True,
    "publish_timestamp": "7d",
}

misp_event_limit_per_page = 100     # Upload Indicators API: Limit memory use when querying MISP for STIX packages

**Comment by cudeso** [comment] 2023-08-04 06:41
The delay is mostly caused by the local misp-stix conversion. Unfortunately that's not something that can be easily solved.
If you're using the Upload Indicators API then there's no local data written (such as state files or other as in the Graph API version).
Can you check with the latest commit? And provide an approx. of how many indicators are returned by MISP (that's in the log file logged with `Received {} indicators in MISP`), and how long the execution takes.

**Comment by PiusO** [comment] 2023-08-04 11:15
So there was an update with script.py, so I've updated that.
The script never completes, I've seen it go on for 5hrs+ with the ""tags": [ "workflow:state="complete""]" filer commented out. Usually I'd see "Received MISP events page 1 with 100 events" for maybe 12 pages of 100 events before freezing, without the workflow filter.
With it I get a negligible amount of indicators.

Somehow a lot of disk space is being consumed in comparison to MGS API, and it's not obvious why, even when i delete the log file, so something is happening somewhere else.



For your request I ran python script.py and the blow has been like that for nearly 2 hours, while the command on the terminal has  finished. This is without workflow complete filter in place.

2023-08-04 09:21:04,631 - misp2sentinel - INFO - Start MISP2Sentinel
2023-08-04 09:21:04,631 - misp2sentinel - INFO - Fetching and parsing data from MISP ...
2023-08-04 09:21:04,631 - misp2sentinel - INFO - Using Microsoft Upload Indicator API

Previously I'd see "Received {374} indicators in MISP". with the workflow complete filter in place.

**Comment by PiusO** [comment] 2023-08-07 10:14
The memory consumption of this new solution is far too much, i don't actually think this is usable, and it's not clear at all where it's all going

**Comment by PiusO** [comment] 2023-08-08 08:17
When i have multiple pages with 100 events that's when the script fails

currently

2023-08-08 06:00:02,144 - misp2sentinel - INFO - Start MISP2Sentinel
2023-08-08 06:00:02,144 - misp2sentinel - INFO - Fetching and parsing data from MISP 
2023-08-08 06:00:02,144 - misp2sentinel - INFO - Using Microsoft Upload Indicator API
2023-08-08 06:04:14,261 - misp2sentinel - INFO - Received MISP events page 1 with 50 events
2023-08-08 06:37:02,388 - misp2sentinel - INFO - Received MISP events page 2 with 10 events
2023-08-08 06:50:21,516 - misp2sentinel - INFO - Received 358596 indicators in MISP
2023-08-08 06:50:21,627 - misp2sentinel - INFO - Start uploading indicators


........


2023-08-08 07:23:43,923 - misp2sentinel - INFO - Indicators sent - request number: 90 / indicators: 100 / remaining: 159496
2023-08-08 07:23:44,468 - misp2sentinel - INFO - Indicators sent - request number: 91 / indicators: 100 / remaining: 159396
2023-08-08 07:24:03,574 - misp2sentinel - ERROR - Error when submitting indicators. {}
2023-08-08 07:24:03,578 - misp2sentinel - INFO - Finished uploading indicators
2023-08-08 07:24:04,324 - misp2sentinel - INFO - End MISP2Sentinel


This has only been possible because i have a script that deletes events in misp

**Comment by PiusO** [comment] 2023-08-09 13:36
Is it okay to delete these files without impact on getting data into sentinel? 


Can you list out other that can be deleted

**Comment by cudeso** [comment] 2023-08-12 13:18
Those files are part of `misp_stix_converter`, they are not installed by the integration. There are a considerable number of files but I don't think they take up that much space.

If you use the Upload Indicators API (which based on the log extracts is the case), there are no temporary files created. The conversion with misp-stix of the MISP events takes some resources, but, as far as I can check, this is still fairly manageable. For example on one of my tests hosts it uploads around 40k indicators a day. This takes 8 minutes.

The error in your log `ERROR - Error when submitting indicators` happens on two reasons, either Microsoft Sentinel does not return an HTTP 200 error code (permission problem, access problem) or it returns an error string in its reply. But that error string should be added to the end of the error message (the code starts around https://github.com/cudeso/misp2sentinel/blob/3d5760e824e6b44bfa24925a5698347a0300c466/RequestManager.py#L218).

There's also a considerable long time (2023-08-08 07:23:44,468 and 2023-08-08 07:24:03,574) between the last successful request and the error message. This kinda gives the hunch of a network issue.

To further debug, can you change the log message in https://github.com/cudeso/misp2sentinel/blob/main/RequestManager.py#L219 to "Error - 219" and the one in https://github.com/cudeso/misp2sentinel/blob/main/RequestManager.py#L226 to "Error - 226". Keep the remaining text. This allows to check which clause causes the error.

To help you with debugging I documented the flow how the script works, this can maybe shed some additional light? Have a look at the updated README.md or https://github.com/cudeso/misp2sentinel/blob/main/docs/base-MISP2Sentinel-workflow.png

**Comment by cudeso** [comment] 2023-08-13 11:21
> To further debug, can you change the log message in https://github.com/cudeso/misp2sentinel/blob/main/RequestManager.py#L219 to "Error - 219" and the one in https://github.com/cudeso/misp2sentinel/blob/main/RequestManager.py#L226 to "Error - 226". Keep the remaining text. This allows to check which clause causes the error.
> 

In the last commit I changed the two error messages so they now indicate if it's either a non-HTTP-200 or an error returned by Sentinel.

**Comment by cudeso** [comment] 2023-08-15 12:14
Ah right. 
The Upload Indicators branch was there to hold the development for the new API pending the time that I moved it into the main branch. This has now been merged all into 'main'. https://github.com/cudeso/misp2sentinel/issues/43 
Apologies for the confusion.

**Closed** 2023-08-18 15:35 UTC
Labels: bug
